/* automatically generated by rust-bindgen 0.69.4 */

pub const __NET_ETHERNET_H: u32 = 1;
pub const _SYS_TYPES_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 35;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const __clock_t_defined: u32 = 1;
pub const __clockid_t_defined: u32 = 1;
pub const __time_t_defined: u32 = 1;
pub const __timer_t_defined: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const __BIT_TYPES_DEFINED__: u32 = 1;
pub const _ENDIAN_H: u32 = 1;
pub const _BITS_ENDIAN_H: u32 = 1;
pub const __LITTLE_ENDIAN: u32 = 1234;
pub const __BIG_ENDIAN: u32 = 4321;
pub const __PDP_ENDIAN: u32 = 3412;
pub const _BITS_ENDIANNESS_H: u32 = 1;
pub const __BYTE_ORDER: u32 = 1234;
pub const __FLOAT_WORD_ORDER: u32 = 1234;
pub const LITTLE_ENDIAN: u32 = 1234;
pub const BIG_ENDIAN: u32 = 4321;
pub const PDP_ENDIAN: u32 = 3412;
pub const BYTE_ORDER: u32 = 1234;
pub const _BITS_BYTESWAP_H: u32 = 1;
pub const _BITS_UINTN_IDENTITY_H: u32 = 1;
pub const _SYS_SELECT_H: u32 = 1;
pub const __sigset_t_defined: u32 = 1;
pub const __timeval_defined: u32 = 1;
pub const _STRUCT_TIMESPEC: u32 = 1;
pub const FD_SETSIZE: u32 = 1024;
pub const _BITS_PTHREADTYPES_COMMON_H: u32 = 1;
pub const _THREAD_SHARED_TYPES_H: u32 = 1;
pub const _BITS_PTHREADTYPES_ARCH_H: u32 = 1;
pub const __SIZEOF_PTHREAD_MUTEX_T: u32 = 40;
pub const __SIZEOF_PTHREAD_ATTR_T: u32 = 56;
pub const __SIZEOF_PTHREAD_RWLOCK_T: u32 = 56;
pub const __SIZEOF_PTHREAD_BARRIER_T: u32 = 32;
pub const __SIZEOF_PTHREAD_MUTEXATTR_T: u32 = 4;
pub const __SIZEOF_PTHREAD_COND_T: u32 = 48;
pub const __SIZEOF_PTHREAD_CONDATTR_T: u32 = 4;
pub const __SIZEOF_PTHREAD_RWLOCKATTR_T: u32 = 8;
pub const __SIZEOF_PTHREAD_BARRIERATTR_T: u32 = 4;
pub const _THREAD_MUTEX_INTERNAL_H: u32 = 1;
pub const __PTHREAD_MUTEX_HAVE_PREV: u32 = 1;
pub const __have_pthread_attr_t: u32 = 1;
pub const _STDINT_H: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const __BITS_PER_LONG: u32 = 64;
pub const ETH_ALEN: u32 = 6;
pub const ETH_TLEN: u32 = 2;
pub const ETH_HLEN: u32 = 14;
pub const ETH_ZLEN: u32 = 60;
pub const ETH_DATA_LEN: u32 = 1500;
pub const ETH_FRAME_LEN: u32 = 1514;
pub const ETH_FCS_LEN: u32 = 4;
pub const ETH_MIN_MTU: u32 = 68;
pub const ETH_MAX_MTU: u32 = 65535;
pub const ETH_P_LOOP: u32 = 96;
pub const ETH_P_PUP: u32 = 512;
pub const ETH_P_PUPAT: u32 = 513;
pub const ETH_P_TSN: u32 = 8944;
pub const ETH_P_ERSPAN2: u32 = 8939;
pub const ETH_P_IP: u32 = 2048;
pub const ETH_P_X25: u32 = 2053;
pub const ETH_P_ARP: u32 = 2054;
pub const ETH_P_BPQ: u32 = 2303;
pub const ETH_P_IEEEPUP: u32 = 2560;
pub const ETH_P_IEEEPUPAT: u32 = 2561;
pub const ETH_P_BATMAN: u32 = 17157;
pub const ETH_P_DEC: u32 = 24576;
pub const ETH_P_DNA_DL: u32 = 24577;
pub const ETH_P_DNA_RC: u32 = 24578;
pub const ETH_P_DNA_RT: u32 = 24579;
pub const ETH_P_LAT: u32 = 24580;
pub const ETH_P_DIAG: u32 = 24581;
pub const ETH_P_CUST: u32 = 24582;
pub const ETH_P_SCA: u32 = 24583;
pub const ETH_P_TEB: u32 = 25944;
pub const ETH_P_RARP: u32 = 32821;
pub const ETH_P_ATALK: u32 = 32923;
pub const ETH_P_AARP: u32 = 33011;
pub const ETH_P_8021Q: u32 = 33024;
pub const ETH_P_ERSPAN: u32 = 35006;
pub const ETH_P_IPX: u32 = 33079;
pub const ETH_P_IPV6: u32 = 34525;
pub const ETH_P_PAUSE: u32 = 34824;
pub const ETH_P_SLOW: u32 = 34825;
pub const ETH_P_WCCP: u32 = 34878;
pub const ETH_P_MPLS_UC: u32 = 34887;
pub const ETH_P_MPLS_MC: u32 = 34888;
pub const ETH_P_ATMMPOA: u32 = 34892;
pub const ETH_P_PPP_DISC: u32 = 34915;
pub const ETH_P_PPP_SES: u32 = 34916;
pub const ETH_P_LINK_CTL: u32 = 34924;
pub const ETH_P_ATMFATE: u32 = 34948;
pub const ETH_P_PAE: u32 = 34958;
pub const ETH_P_AOE: u32 = 34978;
pub const ETH_P_8021AD: u32 = 34984;
pub const ETH_P_802_EX1: u32 = 34997;
pub const ETH_P_PREAUTH: u32 = 35015;
pub const ETH_P_TIPC: u32 = 35018;
pub const ETH_P_LLDP: u32 = 35020;
pub const ETH_P_MRP: u32 = 35043;
pub const ETH_P_MACSEC: u32 = 35045;
pub const ETH_P_8021AH: u32 = 35047;
pub const ETH_P_MVRP: u32 = 35061;
pub const ETH_P_1588: u32 = 35063;
pub const ETH_P_NCSI: u32 = 35064;
pub const ETH_P_PRP: u32 = 35067;
pub const ETH_P_CFM: u32 = 35074;
pub const ETH_P_FCOE: u32 = 35078;
pub const ETH_P_IBOE: u32 = 35093;
pub const ETH_P_TDLS: u32 = 35085;
pub const ETH_P_FIP: u32 = 35092;
pub const ETH_P_80221: u32 = 35095;
pub const ETH_P_HSR: u32 = 35119;
pub const ETH_P_NSH: u32 = 35151;
pub const ETH_P_LOOPBACK: u32 = 36864;
pub const ETH_P_QINQ1: u32 = 37120;
pub const ETH_P_QINQ2: u32 = 37376;
pub const ETH_P_QINQ3: u32 = 37632;
pub const ETH_P_EDSA: u32 = 56026;
pub const ETH_P_DSA_8021Q: u32 = 56027;
pub const ETH_P_IFE: u32 = 60734;
pub const ETH_P_AF_IUCV: u32 = 64507;
pub const ETH_P_802_3_MIN: u32 = 1536;
pub const ETH_P_802_3: u32 = 1;
pub const ETH_P_AX25: u32 = 2;
pub const ETH_P_ALL: u32 = 3;
pub const ETH_P_802_2: u32 = 4;
pub const ETH_P_SNAP: u32 = 5;
pub const ETH_P_DDCMP: u32 = 6;
pub const ETH_P_WAN_PPP: u32 = 7;
pub const ETH_P_PPP_MP: u32 = 8;
pub const ETH_P_LOCALTALK: u32 = 9;
pub const ETH_P_CAN: u32 = 12;
pub const ETH_P_CANFD: u32 = 13;
pub const ETH_P_PPPTALK: u32 = 16;
pub const ETH_P_TR_802_2: u32 = 17;
pub const ETH_P_MOBITEX: u32 = 21;
pub const ETH_P_CONTROL: u32 = 22;
pub const ETH_P_IRDA: u32 = 23;
pub const ETH_P_ECONET: u32 = 24;
pub const ETH_P_HDLC: u32 = 25;
pub const ETH_P_ARCNET: u32 = 26;
pub const ETH_P_DSA: u32 = 27;
pub const ETH_P_TRAILER: u32 = 28;
pub const ETH_P_PHONET: u32 = 245;
pub const ETH_P_IEEE802154: u32 = 246;
pub const ETH_P_CAIF: u32 = 247;
pub const ETH_P_XDSA: u32 = 248;
pub const ETH_P_MAP: u32 = 249;
pub const ETH_P_MCTP: u32 = 250;
pub const __UAPI_DEF_ETHHDR: u32 = 1;
pub const ETHERTYPE_PUP: u32 = 512;
pub const ETHERTYPE_SPRITE: u32 = 1280;
pub const ETHERTYPE_IP: u32 = 2048;
pub const ETHERTYPE_ARP: u32 = 2054;
pub const ETHERTYPE_REVARP: u32 = 32821;
pub const ETHERTYPE_AT: u32 = 32923;
pub const ETHERTYPE_AARP: u32 = 33011;
pub const ETHERTYPE_VLAN: u32 = 33024;
pub const ETHERTYPE_IPX: u32 = 33079;
pub const ETHERTYPE_IPV6: u32 = 34525;
pub const ETHERTYPE_LOOPBACK: u32 = 36864;
pub const ETHER_ADDR_LEN: u32 = 6;
pub const ETHER_TYPE_LEN: u32 = 2;
pub const ETHER_CRC_LEN: u32 = 4;
pub const ETHER_HDR_LEN: u32 = 14;
pub const ETHER_MIN_LEN: u32 = 64;
pub const ETHER_MAX_LEN: u32 = 1518;
pub const ETHERTYPE_TRAIL: u32 = 4096;
pub const ETHERTYPE_NTRAILER: u32 = 16;
pub const ETHERMTU: u32 = 1500;
pub const ETHERMIN: u32 = 46;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
pub const PCI_DOMAIN_LEN: u32 = 5;
pub const PCI_ADDR_LEN: u32 = 15;
pub const PCI_LINK_INFO_LEN: u32 = 10;
pub const HL_FIELD_MAX_SIZE: u32 = 32;
pub const PORTS_ARR_SIZE: u32 = 2;
pub const HLML_DEVICE_MAC_MAX_ADDRESSES: u32 = 48;
pub const HLML_DEVICE_ROW_RPL_MAX: u32 = 32;
pub const HLML_EVENT_ECC_ERR: u32 = 1;
pub const HLML_EVENT_CRITICAL_ERR: u32 = 2;
pub const HLML_EVENT_CLOCK_RATE: u32 = 4;
pub const HLML_EVENT_DRAM_ERR: u32 = 8;
pub const HLML_EVENT_ECC_DERR: u32 = 1;
pub const HLML_EVENT_ECC_SERR: u32 = 16;
pub const HLML_CLOCKS_THROTTLE_REASON_POWER: u32 = 1;
pub const HLML_CLOCKS_THROTTLE_REASON_THERMAL: u32 = 2;
pub const HLML_AFFINITY_SCOPE_NODE: u32 = 0;
pub const HLML_AFFINITY_SCOPE_SOCKET: u32 = 1;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[test]
fn bindgen_test_layout___fsid_t() {
    const UNINIT: ::std::mem::MaybeUninit<__fsid_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__fsid_t>(),
        8usize,
        concat!("Size of: ", stringify!(__fsid_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__fsid_t>(),
        4usize,
        concat!("Alignment of ", stringify!(__fsid_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__val) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__fsid_t),
            "::",
            stringify!(__val)
        )
    );
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type u_char = __u_char;
pub type u_short = __u_short;
pub type u_int = __u_int;
pub type u_long = __u_long;
pub type quad_t = __quad_t;
pub type u_quad_t = __u_quad_t;
pub type fsid_t = __fsid_t;
pub type loff_t = __loff_t;
pub type ino_t = __ino_t;
pub type dev_t = __dev_t;
pub type gid_t = __gid_t;
pub type mode_t = __mode_t;
pub type nlink_t = __nlink_t;
pub type uid_t = __uid_t;
pub type off_t = __off_t;
pub type pid_t = __pid_t;
pub type id_t = __id_t;
pub type daddr_t = __daddr_t;
pub type caddr_t = __caddr_t;
pub type key_t = __key_t;
pub type clock_t = __clock_t;
pub type clockid_t = __clockid_t;
pub type time_t = __time_t;
pub type timer_t = __timer_t;
pub type ulong = ::std::os::raw::c_ulong;
pub type ushort = ::std::os::raw::c_ushort;
pub type uint = ::std::os::raw::c_uint;
pub type u_int8_t = __uint8_t;
pub type u_int16_t = __uint16_t;
pub type u_int32_t = __uint32_t;
pub type u_int64_t = __uint64_t;
pub type register_t = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sigset_t {
    pub __val: [::std::os::raw::c_ulong; 16usize],
}
#[test]
fn bindgen_test_layout___sigset_t() {
    const UNINIT: ::std::mem::MaybeUninit<__sigset_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__sigset_t>(),
        128usize,
        concat!("Size of: ", stringify!(__sigset_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__sigset_t>(),
        8usize,
        concat!("Alignment of ", stringify!(__sigset_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__val) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__sigset_t),
            "::",
            stringify!(__val)
        )
    );
}
pub type sigset_t = __sigset_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timeval {
    pub tv_sec: __time_t,
    pub tv_usec: __suseconds_t,
}
#[test]
fn bindgen_test_layout_timeval() {
    const UNINIT: ::std::mem::MaybeUninit<timeval> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<timeval>(),
        16usize,
        concat!("Size of: ", stringify!(timeval))
    );
    assert_eq!(
        ::std::mem::align_of::<timeval>(),
        8usize,
        concat!("Alignment of ", stringify!(timeval))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tv_sec) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(timeval),
            "::",
            stringify!(tv_sec)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tv_usec) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(timeval),
            "::",
            stringify!(tv_usec)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}
#[test]
fn bindgen_test_layout_timespec() {
    const UNINIT: ::std::mem::MaybeUninit<timespec> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<timespec>(),
        16usize,
        concat!("Size of: ", stringify!(timespec))
    );
    assert_eq!(
        ::std::mem::align_of::<timespec>(),
        8usize,
        concat!("Alignment of ", stringify!(timespec))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tv_sec) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(timespec),
            "::",
            stringify!(tv_sec)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tv_nsec) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(timespec),
            "::",
            stringify!(tv_nsec)
        )
    );
}
pub type suseconds_t = __suseconds_t;
pub type __fd_mask = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fd_set {
    pub __fds_bits: [__fd_mask; 16usize],
}
#[test]
fn bindgen_test_layout_fd_set() {
    const UNINIT: ::std::mem::MaybeUninit<fd_set> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<fd_set>(),
        128usize,
        concat!("Size of: ", stringify!(fd_set))
    );
    assert_eq!(
        ::std::mem::align_of::<fd_set>(),
        8usize,
        concat!("Alignment of ", stringify!(fd_set))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__fds_bits) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(fd_set),
            "::",
            stringify!(__fds_bits)
        )
    );
}
pub type fd_mask = __fd_mask;
extern "C" {
    pub fn select(
        __nfds: ::std::os::raw::c_int,
        __readfds: *mut fd_set,
        __writefds: *mut fd_set,
        __exceptfds: *mut fd_set,
        __timeout: *mut timeval,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn pselect(
        __nfds: ::std::os::raw::c_int,
        __readfds: *mut fd_set,
        __writefds: *mut fd_set,
        __exceptfds: *mut fd_set,
        __timeout: *const timespec,
        __sigmask: *const __sigset_t,
    ) -> ::std::os::raw::c_int;
}
pub type blksize_t = __blksize_t;
pub type blkcnt_t = __blkcnt_t;
pub type fsblkcnt_t = __fsblkcnt_t;
pub type fsfilcnt_t = __fsfilcnt_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __atomic_wide_counter {
    pub __value64: ::std::os::raw::c_ulonglong,
    pub __value32: __atomic_wide_counter__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __atomic_wide_counter__bindgen_ty_1 {
    pub __low: ::std::os::raw::c_uint,
    pub __high: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout___atomic_wide_counter__bindgen_ty_1() {
    const UNINIT: ::std::mem::MaybeUninit<__atomic_wide_counter__bindgen_ty_1> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__atomic_wide_counter__bindgen_ty_1>(),
        8usize,
        concat!("Size of: ", stringify!(__atomic_wide_counter__bindgen_ty_1))
    );
    assert_eq!(
        ::std::mem::align_of::<__atomic_wide_counter__bindgen_ty_1>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(__atomic_wide_counter__bindgen_ty_1)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__low) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__atomic_wide_counter__bindgen_ty_1),
            "::",
            stringify!(__low)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__high) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(__atomic_wide_counter__bindgen_ty_1),
            "::",
            stringify!(__high)
        )
    );
}
#[test]
fn bindgen_test_layout___atomic_wide_counter() {
    const UNINIT: ::std::mem::MaybeUninit<__atomic_wide_counter> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__atomic_wide_counter>(),
        8usize,
        concat!("Size of: ", stringify!(__atomic_wide_counter))
    );
    assert_eq!(
        ::std::mem::align_of::<__atomic_wide_counter>(),
        8usize,
        concat!("Alignment of ", stringify!(__atomic_wide_counter))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__value64) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__atomic_wide_counter),
            "::",
            stringify!(__value64)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__value32) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__atomic_wide_counter),
            "::",
            stringify!(__value32)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __pthread_internal_list {
    pub __prev: *mut __pthread_internal_list,
    pub __next: *mut __pthread_internal_list,
}
#[test]
fn bindgen_test_layout___pthread_internal_list() {
    const UNINIT: ::std::mem::MaybeUninit<__pthread_internal_list> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__pthread_internal_list>(),
        16usize,
        concat!("Size of: ", stringify!(__pthread_internal_list))
    );
    assert_eq!(
        ::std::mem::align_of::<__pthread_internal_list>(),
        8usize,
        concat!("Alignment of ", stringify!(__pthread_internal_list))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__prev) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_internal_list),
            "::",
            stringify!(__prev)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__next) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_internal_list),
            "::",
            stringify!(__next)
        )
    );
}
pub type __pthread_list_t = __pthread_internal_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __pthread_internal_slist {
    pub __next: *mut __pthread_internal_slist,
}
#[test]
fn bindgen_test_layout___pthread_internal_slist() {
    const UNINIT: ::std::mem::MaybeUninit<__pthread_internal_slist> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__pthread_internal_slist>(),
        8usize,
        concat!("Size of: ", stringify!(__pthread_internal_slist))
    );
    assert_eq!(
        ::std::mem::align_of::<__pthread_internal_slist>(),
        8usize,
        concat!("Alignment of ", stringify!(__pthread_internal_slist))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__next) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_internal_slist),
            "::",
            stringify!(__next)
        )
    );
}
pub type __pthread_slist_t = __pthread_internal_slist;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __pthread_mutex_s {
    pub __lock: ::std::os::raw::c_int,
    pub __count: ::std::os::raw::c_uint,
    pub __owner: ::std::os::raw::c_int,
    pub __nusers: ::std::os::raw::c_uint,
    pub __kind: ::std::os::raw::c_int,
    pub __spins: ::std::os::raw::c_short,
    pub __elision: ::std::os::raw::c_short,
    pub __list: __pthread_list_t,
}
#[test]
fn bindgen_test_layout___pthread_mutex_s() {
    const UNINIT: ::std::mem::MaybeUninit<__pthread_mutex_s> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__pthread_mutex_s>(),
        40usize,
        concat!("Size of: ", stringify!(__pthread_mutex_s))
    );
    assert_eq!(
        ::std::mem::align_of::<__pthread_mutex_s>(),
        8usize,
        concat!("Alignment of ", stringify!(__pthread_mutex_s))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__lock) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_mutex_s),
            "::",
            stringify!(__lock)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__count) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_mutex_s),
            "::",
            stringify!(__count)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__owner) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_mutex_s),
            "::",
            stringify!(__owner)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__nusers) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_mutex_s),
            "::",
            stringify!(__nusers)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__kind) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_mutex_s),
            "::",
            stringify!(__kind)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__spins) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_mutex_s),
            "::",
            stringify!(__spins)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__elision) as usize - ptr as usize },
        22usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_mutex_s),
            "::",
            stringify!(__elision)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__list) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_mutex_s),
            "::",
            stringify!(__list)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __pthread_rwlock_arch_t {
    pub __readers: ::std::os::raw::c_uint,
    pub __writers: ::std::os::raw::c_uint,
    pub __wrphase_futex: ::std::os::raw::c_uint,
    pub __writers_futex: ::std::os::raw::c_uint,
    pub __pad3: ::std::os::raw::c_uint,
    pub __pad4: ::std::os::raw::c_uint,
    pub __cur_writer: ::std::os::raw::c_int,
    pub __shared: ::std::os::raw::c_int,
    pub __rwelision: ::std::os::raw::c_schar,
    pub __pad1: [::std::os::raw::c_uchar; 7usize],
    pub __pad2: ::std::os::raw::c_ulong,
    pub __flags: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout___pthread_rwlock_arch_t() {
    const UNINIT: ::std::mem::MaybeUninit<__pthread_rwlock_arch_t> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__pthread_rwlock_arch_t>(),
        56usize,
        concat!("Size of: ", stringify!(__pthread_rwlock_arch_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__pthread_rwlock_arch_t>(),
        8usize,
        concat!("Alignment of ", stringify!(__pthread_rwlock_arch_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__readers) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__readers)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__writers) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__writers)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__wrphase_futex) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__wrphase_futex)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__writers_futex) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__writers_futex)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__pad3) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__pad3)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__pad4) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__pad4)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__cur_writer) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__cur_writer)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__shared) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__shared)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__rwelision) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__rwelision)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__pad1) as usize - ptr as usize },
        33usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__pad1)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__pad2) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__pad2)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__flags) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_rwlock_arch_t),
            "::",
            stringify!(__flags)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __pthread_cond_s {
    pub __wseq: __atomic_wide_counter,
    pub __g1_start: __atomic_wide_counter,
    pub __g_refs: [::std::os::raw::c_uint; 2usize],
    pub __g_size: [::std::os::raw::c_uint; 2usize],
    pub __g1_orig_size: ::std::os::raw::c_uint,
    pub __wrefs: ::std::os::raw::c_uint,
    pub __g_signals: [::std::os::raw::c_uint; 2usize],
}
#[test]
fn bindgen_test_layout___pthread_cond_s() {
    const UNINIT: ::std::mem::MaybeUninit<__pthread_cond_s> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__pthread_cond_s>(),
        48usize,
        concat!("Size of: ", stringify!(__pthread_cond_s))
    );
    assert_eq!(
        ::std::mem::align_of::<__pthread_cond_s>(),
        8usize,
        concat!("Alignment of ", stringify!(__pthread_cond_s))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__wseq) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_cond_s),
            "::",
            stringify!(__wseq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__g1_start) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_cond_s),
            "::",
            stringify!(__g1_start)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__g_refs) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_cond_s),
            "::",
            stringify!(__g_refs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__g_size) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_cond_s),
            "::",
            stringify!(__g_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__g1_orig_size) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_cond_s),
            "::",
            stringify!(__g1_orig_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__wrefs) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_cond_s),
            "::",
            stringify!(__wrefs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__g_signals) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(__pthread_cond_s),
            "::",
            stringify!(__g_signals)
        )
    );
}
pub type __tss_t = ::std::os::raw::c_uint;
pub type __thrd_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __once_flag {
    pub __data: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout___once_flag() {
    const UNINIT: ::std::mem::MaybeUninit<__once_flag> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__once_flag>(),
        4usize,
        concat!("Size of: ", stringify!(__once_flag))
    );
    assert_eq!(
        ::std::mem::align_of::<__once_flag>(),
        4usize,
        concat!("Alignment of ", stringify!(__once_flag))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__data) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__once_flag),
            "::",
            stringify!(__data)
        )
    );
}
pub type pthread_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_mutexattr_t {
    pub __size: [::std::os::raw::c_char; 4usize],
    pub __align: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_pthread_mutexattr_t() {
    const UNINIT: ::std::mem::MaybeUninit<pthread_mutexattr_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<pthread_mutexattr_t>(),
        4usize,
        concat!("Size of: ", stringify!(pthread_mutexattr_t))
    );
    assert_eq!(
        ::std::mem::align_of::<pthread_mutexattr_t>(),
        4usize,
        concat!("Alignment of ", stringify!(pthread_mutexattr_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_mutexattr_t),
            "::",
            stringify!(__size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__align) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_mutexattr_t),
            "::",
            stringify!(__align)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_condattr_t {
    pub __size: [::std::os::raw::c_char; 4usize],
    pub __align: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_pthread_condattr_t() {
    const UNINIT: ::std::mem::MaybeUninit<pthread_condattr_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<pthread_condattr_t>(),
        4usize,
        concat!("Size of: ", stringify!(pthread_condattr_t))
    );
    assert_eq!(
        ::std::mem::align_of::<pthread_condattr_t>(),
        4usize,
        concat!("Alignment of ", stringify!(pthread_condattr_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_condattr_t),
            "::",
            stringify!(__size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__align) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_condattr_t),
            "::",
            stringify!(__align)
        )
    );
}
pub type pthread_key_t = ::std::os::raw::c_uint;
pub type pthread_once_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_attr_t {
    pub __size: [::std::os::raw::c_char; 56usize],
    pub __align: ::std::os::raw::c_long,
}
#[test]
fn bindgen_test_layout_pthread_attr_t() {
    const UNINIT: ::std::mem::MaybeUninit<pthread_attr_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<pthread_attr_t>(),
        56usize,
        concat!("Size of: ", stringify!(pthread_attr_t))
    );
    assert_eq!(
        ::std::mem::align_of::<pthread_attr_t>(),
        8usize,
        concat!("Alignment of ", stringify!(pthread_attr_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_attr_t),
            "::",
            stringify!(__size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__align) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_attr_t),
            "::",
            stringify!(__align)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_mutex_t {
    pub __data: __pthread_mutex_s,
    pub __size: [::std::os::raw::c_char; 40usize],
    pub __align: ::std::os::raw::c_long,
}
#[test]
fn bindgen_test_layout_pthread_mutex_t() {
    const UNINIT: ::std::mem::MaybeUninit<pthread_mutex_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<pthread_mutex_t>(),
        40usize,
        concat!("Size of: ", stringify!(pthread_mutex_t))
    );
    assert_eq!(
        ::std::mem::align_of::<pthread_mutex_t>(),
        8usize,
        concat!("Alignment of ", stringify!(pthread_mutex_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__data) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_mutex_t),
            "::",
            stringify!(__data)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_mutex_t),
            "::",
            stringify!(__size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__align) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_mutex_t),
            "::",
            stringify!(__align)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_cond_t {
    pub __data: __pthread_cond_s,
    pub __size: [::std::os::raw::c_char; 48usize],
    pub __align: ::std::os::raw::c_longlong,
}
#[test]
fn bindgen_test_layout_pthread_cond_t() {
    const UNINIT: ::std::mem::MaybeUninit<pthread_cond_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<pthread_cond_t>(),
        48usize,
        concat!("Size of: ", stringify!(pthread_cond_t))
    );
    assert_eq!(
        ::std::mem::align_of::<pthread_cond_t>(),
        8usize,
        concat!("Alignment of ", stringify!(pthread_cond_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__data) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_cond_t),
            "::",
            stringify!(__data)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_cond_t),
            "::",
            stringify!(__size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__align) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_cond_t),
            "::",
            stringify!(__align)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_rwlock_t {
    pub __data: __pthread_rwlock_arch_t,
    pub __size: [::std::os::raw::c_char; 56usize],
    pub __align: ::std::os::raw::c_long,
}
#[test]
fn bindgen_test_layout_pthread_rwlock_t() {
    const UNINIT: ::std::mem::MaybeUninit<pthread_rwlock_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<pthread_rwlock_t>(),
        56usize,
        concat!("Size of: ", stringify!(pthread_rwlock_t))
    );
    assert_eq!(
        ::std::mem::align_of::<pthread_rwlock_t>(),
        8usize,
        concat!("Alignment of ", stringify!(pthread_rwlock_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__data) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_rwlock_t),
            "::",
            stringify!(__data)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_rwlock_t),
            "::",
            stringify!(__size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__align) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_rwlock_t),
            "::",
            stringify!(__align)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_rwlockattr_t {
    pub __size: [::std::os::raw::c_char; 8usize],
    pub __align: ::std::os::raw::c_long,
}
#[test]
fn bindgen_test_layout_pthread_rwlockattr_t() {
    const UNINIT: ::std::mem::MaybeUninit<pthread_rwlockattr_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<pthread_rwlockattr_t>(),
        8usize,
        concat!("Size of: ", stringify!(pthread_rwlockattr_t))
    );
    assert_eq!(
        ::std::mem::align_of::<pthread_rwlockattr_t>(),
        8usize,
        concat!("Alignment of ", stringify!(pthread_rwlockattr_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_rwlockattr_t),
            "::",
            stringify!(__size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__align) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_rwlockattr_t),
            "::",
            stringify!(__align)
        )
    );
}
pub type pthread_spinlock_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_barrier_t {
    pub __size: [::std::os::raw::c_char; 32usize],
    pub __align: ::std::os::raw::c_long,
}
#[test]
fn bindgen_test_layout_pthread_barrier_t() {
    const UNINIT: ::std::mem::MaybeUninit<pthread_barrier_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<pthread_barrier_t>(),
        32usize,
        concat!("Size of: ", stringify!(pthread_barrier_t))
    );
    assert_eq!(
        ::std::mem::align_of::<pthread_barrier_t>(),
        8usize,
        concat!("Alignment of ", stringify!(pthread_barrier_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_barrier_t),
            "::",
            stringify!(__size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__align) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_barrier_t),
            "::",
            stringify!(__align)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_barrierattr_t {
    pub __size: [::std::os::raw::c_char; 4usize],
    pub __align: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_pthread_barrierattr_t() {
    const UNINIT: ::std::mem::MaybeUninit<pthread_barrierattr_t> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<pthread_barrierattr_t>(),
        4usize,
        concat!("Size of: ", stringify!(pthread_barrierattr_t))
    );
    assert_eq!(
        ::std::mem::align_of::<pthread_barrierattr_t>(),
        4usize,
        concat!("Alignment of ", stringify!(pthread_barrierattr_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_barrierattr_t),
            "::",
            stringify!(__size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__align) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pthread_barrierattr_t),
            "::",
            stringify!(__align)
        )
    );
}
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type __s8 = ::std::os::raw::c_schar;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __s16 = ::std::os::raw::c_short;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __s64 = ::std::os::raw::c_longlong;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fd_set {
    pub fds_bits: [::std::os::raw::c_ulong; 16usize],
}
#[test]
fn bindgen_test_layout___kernel_fd_set() {
    const UNINIT: ::std::mem::MaybeUninit<__kernel_fd_set> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__kernel_fd_set>(),
        128usize,
        concat!("Size of: ", stringify!(__kernel_fd_set))
    );
    assert_eq!(
        ::std::mem::align_of::<__kernel_fd_set>(),
        8usize,
        concat!("Alignment of ", stringify!(__kernel_fd_set))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fds_bits) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__kernel_fd_set),
            "::",
            stringify!(fds_bits)
        )
    );
}
pub type __kernel_sighandler_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>;
pub type __kernel_key_t = ::std::os::raw::c_int;
pub type __kernel_mqd_t = ::std::os::raw::c_int;
pub type __kernel_old_uid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_gid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_dev_t = ::std::os::raw::c_ulong;
pub type __kernel_long_t = ::std::os::raw::c_long;
pub type __kernel_ulong_t = ::std::os::raw::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = ::std::os::raw::c_uint;
pub type __kernel_pid_t = ::std::os::raw::c_int;
pub type __kernel_ipc_pid_t = ::std::os::raw::c_int;
pub type __kernel_uid_t = ::std::os::raw::c_uint;
pub type __kernel_gid_t = ::std::os::raw::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = ::std::os::raw::c_int;
pub type __kernel_uid32_t = ::std::os::raw::c_uint;
pub type __kernel_gid32_t = ::std::os::raw::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fsid_t {
    pub val: [::std::os::raw::c_int; 2usize],
}
#[test]
fn bindgen_test_layout___kernel_fsid_t() {
    const UNINIT: ::std::mem::MaybeUninit<__kernel_fsid_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__kernel_fsid_t>(),
        8usize,
        concat!("Size of: ", stringify!(__kernel_fsid_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__kernel_fsid_t>(),
        4usize,
        concat!("Alignment of ", stringify!(__kernel_fsid_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).val) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__kernel_fsid_t),
            "::",
            stringify!(val)
        )
    );
}
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = ::std::os::raw::c_longlong;
pub type __kernel_old_time_t = __kernel_long_t;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = ::std::os::raw::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = ::std::os::raw::c_int;
pub type __kernel_clockid_t = ::std::os::raw::c_int;
pub type __kernel_caddr_t = *mut ::std::os::raw::c_char;
pub type __kernel_uid16_t = ::std::os::raw::c_ushort;
pub type __kernel_gid16_t = ::std::os::raw::c_ushort;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = ::std::os::raw::c_uint;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ethhdr {
    pub h_dest: [::std::os::raw::c_uchar; 6usize],
    pub h_source: [::std::os::raw::c_uchar; 6usize],
    pub h_proto: __be16,
}
#[test]
fn bindgen_test_layout_ethhdr() {
    const UNINIT: ::std::mem::MaybeUninit<ethhdr> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<ethhdr>(),
        14usize,
        concat!("Size of: ", stringify!(ethhdr))
    );
    assert_eq!(
        ::std::mem::align_of::<ethhdr>(),
        1usize,
        concat!("Alignment of ", stringify!(ethhdr))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_dest) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(ethhdr),
            "::",
            stringify!(h_dest)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_source) as usize - ptr as usize },
        6usize,
        concat!(
            "Offset of field: ",
            stringify!(ethhdr),
            "::",
            stringify!(h_source)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_proto) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(ethhdr),
            "::",
            stringify!(h_proto)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ether_addr {
    pub ether_addr_octet: [u8; 6usize],
}
#[test]
fn bindgen_test_layout_ether_addr() {
    const UNINIT: ::std::mem::MaybeUninit<ether_addr> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<ether_addr>(),
        6usize,
        concat!("Size of: ", stringify!(ether_addr))
    );
    assert_eq!(
        ::std::mem::align_of::<ether_addr>(),
        1usize,
        concat!("Alignment of ", stringify!(ether_addr))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ether_addr_octet) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(ether_addr),
            "::",
            stringify!(ether_addr_octet)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ether_header {
    pub ether_dhost: [u8; 6usize],
    pub ether_shost: [u8; 6usize],
    pub ether_type: u16,
}
#[test]
fn bindgen_test_layout_ether_header() {
    const UNINIT: ::std::mem::MaybeUninit<ether_header> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<ether_header>(),
        14usize,
        concat!("Size of: ", stringify!(ether_header))
    );
    assert_eq!(
        ::std::mem::align_of::<ether_header>(),
        1usize,
        concat!("Alignment of ", stringify!(ether_header))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ether_dhost) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(ether_header),
            "::",
            stringify!(ether_dhost)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ether_shost) as usize - ptr as usize },
        6usize,
        concat!(
            "Offset of field: ",
            stringify!(ether_header),
            "::",
            stringify!(ether_shost)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ether_type) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(ether_header),
            "::",
            stringify!(ether_type)
        )
    );
}
pub type hlml_affinity_scope_t = ::std::os::raw::c_uint;
pub const hlml_return_HLML_SUCCESS: hlml_return = 0;
pub const hlml_return_HLML_ERROR_UNINITIALIZED: hlml_return = 1;
pub const hlml_return_HLML_ERROR_INVALID_ARGUMENT: hlml_return = 2;
pub const hlml_return_HLML_ERROR_NOT_SUPPORTED: hlml_return = 3;
pub const hlml_return_HLML_ERROR_ALREADY_INITIALIZED: hlml_return = 5;
pub const hlml_return_HLML_ERROR_NOT_FOUND: hlml_return = 6;
pub const hlml_return_HLML_ERROR_INSUFFICIENT_SIZE: hlml_return = 7;
pub const hlml_return_HLML_ERROR_DRIVER_NOT_LOADED: hlml_return = 9;
pub const hlml_return_HLML_ERROR_TIMEOUT: hlml_return = 10;
pub const hlml_return_HLML_ERROR_AIP_IS_LOST: hlml_return = 15;
pub const hlml_return_HLML_ERROR_MEMORY: hlml_return = 20;
pub const hlml_return_HLML_ERROR_NO_DATA: hlml_return = 21;
pub const hlml_return_HLML_ERROR_UNKNOWN: hlml_return = 49;
pub type hlml_return = ::std::os::raw::c_uint;
pub use self::hlml_return as hlml_return_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_pci_cap {
    pub link_speed: [::std::os::raw::c_char; 10usize],
    pub link_width: [::std::os::raw::c_char; 10usize],
}
#[test]
fn bindgen_test_layout_hlml_pci_cap() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_pci_cap> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_pci_cap>(),
        20usize,
        concat!("Size of: ", stringify!(hlml_pci_cap))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_pci_cap>(),
        1usize,
        concat!("Alignment of ", stringify!(hlml_pci_cap))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).link_speed) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pci_cap),
            "::",
            stringify!(link_speed)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).link_width) as usize - ptr as usize },
        10usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pci_cap),
            "::",
            stringify!(link_width)
        )
    );
}
pub type hlml_pci_cap_t = hlml_pci_cap;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_pci_info {
    pub bus: ::std::os::raw::c_uint,
    pub bus_id: [::std::os::raw::c_char; 15usize],
    pub device: ::std::os::raw::c_uint,
    pub domain: ::std::os::raw::c_uint,
    pub pci_device_id: ::std::os::raw::c_uint,
    pub caps: hlml_pci_cap_t,
}
#[test]
fn bindgen_test_layout_hlml_pci_info() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_pci_info> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_pci_info>(),
        52usize,
        concat!("Size of: ", stringify!(hlml_pci_info))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_pci_info>(),
        4usize,
        concat!("Alignment of ", stringify!(hlml_pci_info))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bus) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pci_info),
            "::",
            stringify!(bus)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bus_id) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pci_info),
            "::",
            stringify!(bus_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).device) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pci_info),
            "::",
            stringify!(device)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).domain) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pci_info),
            "::",
            stringify!(domain)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pci_device_id) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pci_info),
            "::",
            stringify!(pci_device_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).caps) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pci_info),
            "::",
            stringify!(caps)
        )
    );
}
pub type hlml_pci_info_t = hlml_pci_info;
pub const hlml_clock_type_HLML_CLOCK_SOC: hlml_clock_type = 0;
pub const hlml_clock_type_HLML_CLOCK_IC: hlml_clock_type = 1;
pub const hlml_clock_type_HLML_CLOCK_MME: hlml_clock_type = 2;
pub const hlml_clock_type_HLML_CLOCK_TPC: hlml_clock_type = 3;
pub const hlml_clock_type_HLML_CLOCK_COUNT: hlml_clock_type = 4;
pub type hlml_clock_type = ::std::os::raw::c_uint;
pub use self::hlml_clock_type as hlml_clock_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_utilization {
    pub aip: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout_hlml_utilization() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_utilization> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_utilization>(),
        4usize,
        concat!("Size of: ", stringify!(hlml_utilization))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_utilization>(),
        4usize,
        concat!("Alignment of ", stringify!(hlml_utilization))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).aip) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_utilization),
            "::",
            stringify!(aip)
        )
    );
}
pub type hlml_utilization_t = hlml_utilization;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_memory {
    pub free: ::std::os::raw::c_ulonglong,
    pub total: ::std::os::raw::c_ulonglong,
    pub used: ::std::os::raw::c_ulonglong,
}
#[test]
fn bindgen_test_layout_hlml_memory() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_memory> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_memory>(),
        24usize,
        concat!("Size of: ", stringify!(hlml_memory))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_memory>(),
        8usize,
        concat!("Alignment of ", stringify!(hlml_memory))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).free) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_memory),
            "::",
            stringify!(free)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).total) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_memory),
            "::",
            stringify!(total)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).used) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_memory),
            "::",
            stringify!(used)
        )
    );
}
pub type hlml_memory_t = hlml_memory;
pub const hlml_temperature_sensors_HLML_TEMPERATURE_ON_AIP: hlml_temperature_sensors = 0;
pub const hlml_temperature_sensors_HLML_TEMPERATURE_ON_BOARD: hlml_temperature_sensors = 1;
pub const hlml_temperature_sensors_HLML_TEMPERATURE_OTHER: hlml_temperature_sensors = 2;
pub type hlml_temperature_sensors = ::std::os::raw::c_uint;
pub use self::hlml_temperature_sensors as hlml_temperature_sensors_t;
pub const hlml_temperature_thresholds_HLML_TEMPERATURE_THRESHOLD_SHUTDOWN:
    hlml_temperature_thresholds = 0;
pub const hlml_temperature_thresholds_HLML_TEMPERATURE_THRESHOLD_SLOWDOWN:
    hlml_temperature_thresholds = 1;
pub const hlml_temperature_thresholds_HLML_TEMPERATURE_THRESHOLD_MEM_MAX:
    hlml_temperature_thresholds = 2;
pub const hlml_temperature_thresholds_HLML_TEMPERATURE_THRESHOLD_GPU_MAX:
    hlml_temperature_thresholds = 3;
pub const hlml_temperature_thresholds_HLML_TEMPERATURE_THRESHOLD_COUNT:
    hlml_temperature_thresholds = 4;
pub type hlml_temperature_thresholds = ::std::os::raw::c_uint;
pub use self::hlml_temperature_thresholds as hlml_temperature_thresholds_t;
pub const hlml_enable_state_HLML_FEATURE_DISABLED: hlml_enable_state = 0;
pub const hlml_enable_state_HLML_FEATURE_ENABLED: hlml_enable_state = 1;
pub type hlml_enable_state = ::std::os::raw::c_uint;
pub use self::hlml_enable_state as hlml_enable_state_t;
pub const hlml_p_states_HLML_PSTATE_0: hlml_p_states = 0;
pub const hlml_p_states_HLML_PSTATE_UNKNOWN: hlml_p_states = 32;
pub type hlml_p_states = ::std::os::raw::c_uint;
pub use self::hlml_p_states as hlml_p_states_t;
pub const hlml_memory_error_type_HLML_MEMORY_ERROR_TYPE_CORRECTED: hlml_memory_error_type = 0;
pub const hlml_memory_error_type_HLML_MEMORY_ERROR_TYPE_UNCORRECTED: hlml_memory_error_type = 1;
pub const hlml_memory_error_type_HLML_MEMORY_ERROR_TYPE_COUNT: hlml_memory_error_type = 2;
pub type hlml_memory_error_type = ::std::os::raw::c_uint;
pub use self::hlml_memory_error_type as hlml_memory_error_type_t;
pub const hlml_memory_location_type_HLML_MEMORY_LOCATION_SRAM: hlml_memory_location_type = 0;
pub const hlml_memory_location_type_HLML_MEMORY_LOCATION_DRAM: hlml_memory_location_type = 1;
pub const hlml_memory_location_type_HLML_MEMORY_LOCATION_COUNT: hlml_memory_location_type = 2;
pub type hlml_memory_location_type = ::std::os::raw::c_uint;
pub use self::hlml_memory_location_type as hlml_memory_location_type_t;
pub const hlml_ecc_counter_type_HLML_VOLATILE_ECC: hlml_ecc_counter_type = 0;
pub const hlml_ecc_counter_type_HLML_AGGREGATE_ECC: hlml_ecc_counter_type = 1;
pub const hlml_ecc_counter_type_HLML_ECC_COUNTER_TYPE_COUNT: hlml_ecc_counter_type = 2;
pub type hlml_ecc_counter_type = ::std::os::raw::c_uint;
pub use self::hlml_ecc_counter_type as hlml_ecc_counter_type_t;
pub const hlml_err_inject_HLML_ERR_INJECT_ENDLESS_COMMAND: hlml_err_inject = 0;
pub const hlml_err_inject_HLML_ERR_INJECT_NON_FATAL_EVENT: hlml_err_inject = 1;
pub const hlml_err_inject_HLML_ERR_INJECT_FATAL_EVENT: hlml_err_inject = 2;
pub const hlml_err_inject_HLML_ERR_INJECT_LOSS_OF_HEARTBEAT: hlml_err_inject = 3;
pub const hlml_err_inject_HLML_ERR_INJECT_THERMAL_EVENT: hlml_err_inject = 4;
pub const hlml_err_inject_HLML_ERR_INJECT_COUNT: hlml_err_inject = 5;
pub type hlml_err_inject = ::std::os::raw::c_uint;
pub use self::hlml_err_inject as hlml_err_inject_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_pcb_info {
    pub pcb_ver: [::std::os::raw::c_char; 32usize],
    pub pcb_assembly_ver: [::std::os::raw::c_char; 32usize],
}
#[test]
fn bindgen_test_layout_hlml_pcb_info() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_pcb_info> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_pcb_info>(),
        64usize,
        concat!("Size of: ", stringify!(hlml_pcb_info))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_pcb_info>(),
        1usize,
        concat!("Alignment of ", stringify!(hlml_pcb_info))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pcb_ver) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pcb_info),
            "::",
            stringify!(pcb_ver)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pcb_assembly_ver) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_pcb_info),
            "::",
            stringify!(pcb_assembly_ver)
        )
    );
}
pub type hlml_pcb_info_t = hlml_pcb_info;
pub type hlml_device_t = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_event_data {
    pub device: hlml_device_t,
    pub event_type: ::std::os::raw::c_ulonglong,
}
#[test]
fn bindgen_test_layout_hlml_event_data() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_event_data> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_event_data>(),
        16usize,
        concat!("Size of: ", stringify!(hlml_event_data))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_event_data>(),
        8usize,
        concat!("Alignment of ", stringify!(hlml_event_data))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).device) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_event_data),
            "::",
            stringify!(device)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).event_type) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_event_data),
            "::",
            stringify!(event_type)
        )
    );
}
pub type hlml_event_data_t = hlml_event_data;
pub type hlml_event_set_t = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_mac_info {
    pub addr: [::std::os::raw::c_uchar; 6usize],
    pub id: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_hlml_mac_info() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_mac_info> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_mac_info>(),
        12usize,
        concat!("Size of: ", stringify!(hlml_mac_info))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_mac_info>(),
        4usize,
        concat!("Alignment of ", stringify!(hlml_mac_info))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).addr) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_mac_info),
            "::",
            stringify!(addr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).id) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_mac_info),
            "::",
            stringify!(id)
        )
    );
}
pub type hlml_mac_info_t = hlml_mac_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_nic_stats_info {
    pub port: u32,
    pub str_buf: *mut ::std::os::raw::c_char,
    pub val_buf: *mut u64,
    pub num_of_counters_out: *mut u32,
}
#[test]
fn bindgen_test_layout_hlml_nic_stats_info() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_nic_stats_info> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_nic_stats_info>(),
        32usize,
        concat!("Size of: ", stringify!(hlml_nic_stats_info))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_nic_stats_info>(),
        8usize,
        concat!("Alignment of ", stringify!(hlml_nic_stats_info))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).port) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_nic_stats_info),
            "::",
            stringify!(port)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).str_buf) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_nic_stats_info),
            "::",
            stringify!(str_buf)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).val_buf) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_nic_stats_info),
            "::",
            stringify!(val_buf)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).num_of_counters_out) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_nic_stats_info),
            "::",
            stringify!(num_of_counters_out)
        )
    );
}
pub type hlml_nic_stats_info_t = hlml_nic_stats_info;
pub const hlml_pcie_util_counter_HLML_PCIE_UTIL_TX_BYTES: hlml_pcie_util_counter = 0;
pub const hlml_pcie_util_counter_HLML_PCIE_UTIL_RX_BYTES: hlml_pcie_util_counter = 1;
pub const hlml_pcie_util_counter_HLML_PCIE_UTIL_COUNT: hlml_pcie_util_counter = 2;
pub type hlml_pcie_util_counter = ::std::os::raw::c_uint;
pub use self::hlml_pcie_util_counter as hlml_pcie_util_counter_t;
pub const hlml_perf_policy_type_HLML_PERF_POLICY_POWER: hlml_perf_policy_type = 0;
pub const hlml_perf_policy_type_HLML_PERF_POLICY_THERMAL: hlml_perf_policy_type = 1;
pub const hlml_perf_policy_type_HLML_PERF_POLICY_COUNT: hlml_perf_policy_type = 2;
pub type hlml_perf_policy_type = ::std::os::raw::c_uint;
pub use self::hlml_perf_policy_type as hlml_perf_policy_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_violation_time {
    pub reference_time: ::std::os::raw::c_ulonglong,
    pub violation_time: ::std::os::raw::c_ulonglong,
}
#[test]
fn bindgen_test_layout_hlml_violation_time() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_violation_time> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_violation_time>(),
        16usize,
        concat!("Size of: ", stringify!(hlml_violation_time))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_violation_time>(),
        8usize,
        concat!("Alignment of ", stringify!(hlml_violation_time))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).reference_time) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_violation_time),
            "::",
            stringify!(reference_time)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).violation_time) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_violation_time),
            "::",
            stringify!(violation_time)
        )
    );
}
pub type hlml_violation_time_t = hlml_violation_time;
pub const hlml_row_replacement_cause_HLML_ROW_REPLACEMENT_CAUSE_MULTIPLE_SINGLE_BIT_ECC_ERRORS:
    hlml_row_replacement_cause = 0;
pub const hlml_row_replacement_cause_HLML_ROW_REPLACEMENT_CAUSE_DOUBLE_BIT_ECC_ERROR:
    hlml_row_replacement_cause = 1;
pub const hlml_row_replacement_cause_HLML_ROW_REPLACEMENT_CAUSE_COUNT: hlml_row_replacement_cause =
    2;
pub type hlml_row_replacement_cause = ::std::os::raw::c_uint;
pub use self::hlml_row_replacement_cause as hlml_row_replacement_cause_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlml_row_address {
    pub hbm_idx: u8,
    pub pc: u8,
    pub sid: u8,
    pub bank_idx: u8,
    pub row_addr: u16,
}
#[test]
fn bindgen_test_layout_hlml_row_address() {
    const UNINIT: ::std::mem::MaybeUninit<hlml_row_address> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<hlml_row_address>(),
        6usize,
        concat!("Size of: ", stringify!(hlml_row_address))
    );
    assert_eq!(
        ::std::mem::align_of::<hlml_row_address>(),
        2usize,
        concat!("Alignment of ", stringify!(hlml_row_address))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).hbm_idx) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_row_address),
            "::",
            stringify!(hbm_idx)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pc) as usize - ptr as usize },
        1usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_row_address),
            "::",
            stringify!(pc)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sid) as usize - ptr as usize },
        2usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_row_address),
            "::",
            stringify!(sid)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bank_idx) as usize - ptr as usize },
        3usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_row_address),
            "::",
            stringify!(bank_idx)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).row_addr) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(hlml_row_address),
            "::",
            stringify!(row_addr)
        )
    );
}
pub type hlml_row_address_t = hlml_row_address;
extern "C" {
    pub fn hlml_init() -> hlml_return_t;
}
extern "C" {
    pub fn hlml_init_with_flags(flags: ::std::os::raw::c_uint) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_shutdown() -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_count(device_count: *mut ::std::os::raw::c_uint) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_handle_by_pci_bus_id(
        pci_addr: *const ::std::os::raw::c_char,
        device: *mut hlml_device_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_handle_by_index(
        index: ::std::os::raw::c_uint,
        device: *mut hlml_device_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_handle_by_UUID(
        uuid: *const ::std::os::raw::c_char,
        device: *mut hlml_device_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_name(
        device: hlml_device_t,
        name: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_pci_info(
        device: hlml_device_t,
        pci: *mut hlml_pci_info_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_clock_info(
        device: hlml_device_t,
        type_: hlml_clock_type_t,
        clock: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_max_clock_info(
        device: hlml_device_t,
        type_: hlml_clock_type_t,
        clock: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_utilization_rates(
        device: hlml_device_t,
        utilization: *mut hlml_utilization_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_memory_info(
        device: hlml_device_t,
        memory: *mut hlml_memory_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_temperature(
        device: hlml_device_t,
        sensor_type: hlml_temperature_sensors_t,
        temp: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_temperature_threshold(
        device: hlml_device_t,
        threshold_type: hlml_temperature_thresholds_t,
        temp: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_persistence_mode(
        device: hlml_device_t,
        mode: *mut hlml_enable_state_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_performance_state(
        device: hlml_device_t,
        p_state: *mut hlml_p_states_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_power_usage(
        device: hlml_device_t,
        power: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_power_management_default_limit(
        device: hlml_device_t,
        default_limit: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_ecc_mode(
        device: hlml_device_t,
        current: *mut hlml_enable_state_t,
        pending: *mut hlml_enable_state_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_total_ecc_errors(
        device: hlml_device_t,
        error_type: hlml_memory_error_type_t,
        counter_type: hlml_ecc_counter_type_t,
        ecc_counts: *mut ::std::os::raw::c_ulonglong,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_memory_error_counter(
        device: hlml_device_t,
        error_type: hlml_memory_error_type_t,
        counter_type: hlml_ecc_counter_type_t,
        location: hlml_memory_location_type_t,
        ecc_counts: *mut ::std::os::raw::c_ulonglong,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_uuid(
        device: hlml_device_t,
        uuid: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_minor_number(
        device: hlml_device_t,
        minor_number: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_register_events(
        device: hlml_device_t,
        event_types: ::std::os::raw::c_ulonglong,
        set: hlml_event_set_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_event_set_create(set: *mut hlml_event_set_t) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_event_set_free(set: hlml_event_set_t) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_event_set_wait(
        set: hlml_event_set_t,
        data: *mut hlml_event_data_t,
        timeoutms: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_mac_info(
        device: hlml_device_t,
        mac_info: *mut hlml_mac_info_t,
        mac_info_size: ::std::os::raw::c_uint,
        start_mac_id: ::std::os::raw::c_uint,
        actual_mac_count: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_err_inject(
        device: hlml_device_t,
        err_type: hlml_err_inject_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_hl_revision(
        device: hlml_device_t,
        hl_revision: *mut ::std::os::raw::c_int,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_pcb_info(
        device: hlml_device_t,
        pcb: *mut hlml_pcb_info_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_serial(
        device: hlml_device_t,
        serial: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_module_id(
        device: hlml_device_t,
        module_id: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_board_id(
        device: hlml_device_t,
        board_id: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_pcie_throughput(
        device: hlml_device_t,
        counter: hlml_pcie_util_counter_t,
        value: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_pcie_replay_counter(
        device: hlml_device_t,
        value: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_curr_pcie_link_generation(
        device: hlml_device_t,
        curr_link_gen: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_curr_pcie_link_width(
        device: hlml_device_t,
        curr_link_width: *mut ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_current_clocks_throttle_reasons(
        device: hlml_device_t,
        clocks_throttle_reasons: *mut ::std::os::raw::c_ulonglong,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_total_energy_consumption(
        device: hlml_device_t,
        energy: *mut ::std::os::raw::c_ulonglong,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_mac_addr_info(
        device: hlml_device_t,
        mask: *mut u64,
        ext_mask: *mut u64,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_nic_get_link(device: hlml_device_t, port: u32, up: *mut bool) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_nic_get_statistics(
        device: hlml_device_t,
        stats_info: *mut hlml_nic_stats_info_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_clear_cpu_affinity(device: hlml_device_t) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_cpu_affinity(
        device: hlml_device_t,
        cpu_set_size: ::std::os::raw::c_uint,
        cpu_set: *mut ::std::os::raw::c_ulong,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_cpu_affinity_within_scope(
        device: hlml_device_t,
        cpu_set_size: ::std::os::raw::c_uint,
        cpu_set: *mut ::std::os::raw::c_ulong,
        scope: hlml_affinity_scope_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_memory_affinity(
        device: hlml_device_t,
        node_set_size: ::std::os::raw::c_uint,
        node_set: *mut ::std::os::raw::c_ulong,
        scope: hlml_affinity_scope_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_set_cpu_affinity(device: hlml_device_t) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_violation_status(
        device: hlml_device_t,
        perf_policy_type: hlml_perf_policy_type_t,
        viol_time: *mut hlml_violation_time_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_replaced_rows(
        device: hlml_device_t,
        cause: hlml_row_replacement_cause_t,
        row_count: *mut ::std::os::raw::c_uint,
        addresses: *mut hlml_row_address_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_device_get_replaced_rows_pending_status(
        device: hlml_device_t,
        is_pending: *mut hlml_enable_state_t,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_hlml_version(
        version: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_driver_version(
        driver_version: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_model_number(
        device: hlml_device_t,
        model_number: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_serial_number(
        device: hlml_device_t,
        serial_number: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_firmware_fit_version(
        device: hlml_device_t,
        firmware_fit: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_firmware_spi_version(
        device: hlml_device_t,
        firmware_spi: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_fw_boot_version(
        device: hlml_device_t,
        fw_boot_version: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_fw_os_version(
        device: hlml_device_t,
        fw_os_version: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
extern "C" {
    pub fn hlml_get_cpld_version(
        device: hlml_device_t,
        cpld_version: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> hlml_return_t;
}
